Try easier prefix.

diff --git a/.github/workflows/debootstrap.yml b/.github/workflows/debootstrap.yml
--- a/.github/workflows/debootstrap.yml
+++ b/.github/workflows/debootstrap.yml
@@ -14,6 +14,9 @@ jobs:
         architecture:
           - amd64
           - arm64
+        distribution:
+          - bookworm
+          - trixie
         protocol:
           - http
           - https
@@ -21,6 +24,8 @@ jobs:
           - standard
           - buildd
           - minbase
+      env:
+        prefix: debian-${{ matrix.distribution }}-${{ matrix.architecture }}-${{ matrix.variant }}-${{ matrix.protocol }}
     steps:
       - name: Get Repository
         uses: actions/checkout@v4
@@ -40,125 +45,131 @@ jobs:
             bootstrap
           timestamp="$(git log -1 --format=tformat:%cd \
             --date=format:%Y-%m-%dT%H:%M:%SZ "${GITHUB_SHA}")"
-          LC_ALL=C sudo tar --create --xz --file ../rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz \
+          LC_ALL=C sudo tar --create --xz --file ../${prefix}-rootfs.tar.xz \
             --directory rootfs --sort name --numeric-owner \
             --mtime "${timestamp}" --clamp-mtime .
-          tar --create --xz --file ../cache-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz cache
+          tar --create --xz --file ../${prefix}-cache.tar.xz cache
       - name: Archive Root Filesystem
         uses: actions/upload-artifact@v4
         with:
-          path: rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-          name: rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
+          path: ${prefix}-rootfs.tar.xz
+          name: ${prefix}-rootfs.tar.xz
       - name: Archive Cache
         uses: actions/upload-artifact@v4
         with:
-          path: cache-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-          name: cache-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-  bootstrap-offline:
-    runs-on: ubuntu-latest
-    needs: bootstrap
-    strategy:
-      matrix:
-        architecture:
-          - amd64
-          - arm64
-        protocol:
-          - http
-          - https
-        variant:
-          - standard
-          - buildd
-          - minbase
-    steps:
-      - name: Get Repository
-        uses: actions/checkout@v4
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Restore Cache
-        uses: actions/download-artifact@v4
-        with:
-          name: cache-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-      - name: Run Offline Bootstrap
-        run: |
-          cd bootstrap
-          sudo tar --extract --xz --file ../cache-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-          docker build --file Containerfile --target bootstrap --tag bootstrap .
-          docker run \
-            --env architecture=${{ matrix.architecture }} \
-            --env keyserver=none \
-            --env mirror=${{ matrix.protocol }}://deb.debian.org/debian \
-            --env variant=${{ matrix.variant }} \
-            --net none \
-            --privileged \
-            --volume "$(pwd)/cache:/cache:ro" \
-            --volume "$(pwd)/rootfs:/debian" \
-            bootstrap
-          timestamp="$(git log -1 --format=tformat:%cd \
-            --date=format:%Y-%m-%dT%H:%M:%SZ "${GITHUB_SHA}")"
-          LC_ALL=C sudo tar --create --xz --file ../offline-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz \
-            --directory rootfs --sort name --numeric-owner \
-            --mtime "${timestamp}" --clamp-mtime .
-      - name: Get Original Bootstrap Rootfs
-        uses: actions/download-artifact@v4
-        with:
-          name: rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-      - name: Ensure Identical Artifacts
-        run: |
-          sha256sum rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz offline-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-          if ! diff rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz offline-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz; then
-            sudo apt-get update
-            sudo apt-get install --yes diffoscope
-            diffoscope rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz offline-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-          fi
-  debootstrap:
-    runs-on: ubuntu-latest
-    needs: bootstrap
-    strategy:
-      matrix:
-        architecture:
-          - amd64
-          - arm64
-        protocol:
-          - http
-          - https
-        variant:
-          - standard
-          - buildd
-          - minbase
-    steps:
-      - name: Get Repository
-        uses: actions/checkout@v4
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-      - name: Run debootstrap
-        run: |
-          cd bootstrap
-          docker build --file Containerfile --target debootstrap \
-            --tag debootstrap .
-          case "${{ matrix.variant }}" in
-              standard) docker run --privileged --volume "$(pwd):/out" debootstrap --arch ${{ matrix.architecture }}                                bookworm /out/rootfs ${{ matrix.protocol }}://deb.debian.org/debian ;;
-              buildd)   docker run --privileged --volume "$(pwd):/out" debootstrap --arch ${{ matrix.architecture }} --merged-usr --variant=buildd  bookworm /out/rootfs ${{ matrix.protocol }}://deb.debian.org/debian ;;
-              minbase)  docker run --privileged --volume "$(pwd):/out" debootstrap --arch ${{ matrix.architecture }}              --variant=minbase bookworm /out/rootfs ${{ matrix.protocol }}://deb.debian.org/debian ;;
-              *) echo "Bad variant." && exit 1 ;;
-          esac
-          sudo ./cleanup-debootstrap rootfs
-          timestamp="$(git log -1 --format=tformat:%cd \
-            --date=format:%Y-%m-%dT%H:%M:%SZ "${GITHUB_SHA}")"
-          LC_ALL=C sudo tar --create --xz --file ../debootstrap-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz \
-            --directory rootfs --sort name --numeric-owner \
-            --mtime "${timestamp}" --clamp-mtime .
-      - name: Get Original Bootstrap Rootfs
-        uses: actions/download-artifact@v4
-        with:
-          name: rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-      - name: Ensure Identical Artifacts
-        run: |
-          sha256sum rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz debootstrap-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-          if ! diff rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz debootstrap-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz; then
-            sudo apt-get update
-            sudo apt-get install --yes diffoscope
-            diffoscope rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz debootstrap-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
-          fi
+          path: ${prefix}-rootfs.tar.xz
+          name: ${prefix}-rootfs.tar.xz
+  #  bootstrap-offline:
+  #    runs-on: ubuntu-latest
+  #    needs: bootstrap
+  #    strategy:
+  #      matrix:
+  #        architecture:
+  #          - amd64
+  #          - arm64
+  #        distribution:
+  #          - bookworm
+  #          - trixie
+  #        protocol:
+  #          - http
+  #          - https
+  #        variant:
+  #          - standard
+  #          - buildd
+  #          - minbase
+  #    steps:
+  #      - name: Get Repository
+  #        uses: actions/checkout@v4
+  #      - name: Set up QEMU
+  #        uses: docker/setup-qemu-action@v3
+  #      - name: Restore Cache
+  #        uses: actions/download-artifact@v4
+  #        with:
+  #          name: cache-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
+  #      - name: Run Offline Bootstrap
+  #        run: |
+  #          cd bootstrap
+  #          sudo tar --extract --xz --file ../cache-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
+  #          docker build --file Containerfile --target bootstrap --tag bootstrap .
+  #          docker run \
+  #            --env architecture=${{ matrix.architecture }} \
+  #            --env keyserver=none \
+  #            --env mirror=${{ matrix.protocol }}://deb.debian.org/debian \
+  #            --env variant=${{ matrix.variant }} \
+  #            --net none \
+  #            --privileged \
+  #            --volume "$(pwd)/cache:/cache:ro" \
+  #            --volume "$(pwd)/rootfs:/debian" \
+  #            bootstrap
+  #          timestamp="$(git log -1 --format=tformat:%cd \
+  #            --date=format:%Y-%m-%dT%H:%M:%SZ "${GITHUB_SHA}")"
+  #          LC_ALL=C sudo tar --create --xz --file ../offline-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz \
+  #            --directory rootfs --sort name --numeric-owner \
+  #            --mtime "${timestamp}" --clamp-mtime .
+  #      - name: Get Original Bootstrap Rootfs
+  #        uses: actions/download-artifact@v4
+  #        with:
+  #          name: rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
+  #      - name: Ensure Identical Artifacts
+  #        run: |
+  #          sha256sum rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz offline-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
+  #          if ! diff rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz offline-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz; then
+  #            sudo apt-get update
+  #            sudo apt-get install --yes diffoscope
+  #            diffoscope rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz offline-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
+  #          fi
+  #  debootstrap:
+  #    runs-on: ubuntu-latest
+  #    needs: bootstrap
+  #    strategy:
+  #      matrix:
+  #        architecture:
+  #          - amd64
+  #          - arm64
+  #        distribution:
+  #          - bookworm
+  #          - trixie
+  #        protocol:
+  #          - http
+  #          - https
+  #        variant:
+  #          - standard
+  #          - buildd
+  #          - minbase
+  #    steps:
+  #      - name: Get Repository
+  #        uses: actions/checkout@v4
+  #      - name: Set up QEMU
+  #        uses: docker/setup-qemu-action@v3
+  #      - name: Run debootstrap
+  #        run: |
+  #          cd bootstrap
+  #          docker build --file Containerfile --target debootstrap \
+  #            --tag debootstrap .
+  #          case "${{ matrix.variant }}" in
+  #              standard) docker run --privileged --volume "$(pwd):/out" debootstrap --arch ${{ matrix.architecture }}                                bookworm /out/rootfs ${{ matrix.protocol }}://deb.debian.org/debian ;;
+  #              buildd)   docker run --privileged --volume "$(pwd):/out" debootstrap --arch ${{ matrix.architecture }} --merged-usr --variant=buildd  bookworm /out/rootfs ${{ matrix.protocol }}://deb.debian.org/debian ;;
+  #              minbase)  docker run --privileged --volume "$(pwd):/out" debootstrap --arch ${{ matrix.architecture }}              --variant=minbase bookworm /out/rootfs ${{ matrix.protocol }}://deb.debian.org/debian ;;
+  #              *) echo "Bad variant." && exit 1 ;;
+  #          esac
+  #          sudo ./cleanup-debootstrap rootfs
+  #          timestamp="$(git log -1 --format=tformat:%cd \
+  #            --date=format:%Y-%m-%dT%H:%M:%SZ "${GITHUB_SHA}")"
+  #          LC_ALL=C sudo tar --create --xz --file ../debootstrap-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz \
+  #            --directory rootfs --sort name --numeric-owner \
+  #            --mtime "${timestamp}" --clamp-mtime .
+  #      - name: Get Original Bootstrap Rootfs
+  #        uses: actions/download-artifact@v4
+  #        with:
+  #          name: rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
+  #      - name: Ensure Identical Artifacts
+  #        run: |
+  #          sha256sum rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz debootstrap-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
+  #          if ! diff rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz debootstrap-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz; then
+  #            sudo apt-get update
+  #            sudo apt-get install --yes diffoscope
+  #            diffoscope rootfs-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz debootstrap-${{ matrix.protocol }}-${{ matrix.variant }}-${{ matrix.architecture }}.tar.xz
+  #          fi
   # SKIP FOR NOW
   #attestation:
   #  runs-on: ubuntu-latest
